DROP TABLE Student;
DROP TABLE Fakultet;
GO

CREATE TABLE Fakultet (
	FakultetID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Naziv VARCHAR(50) NOT NULL,
	Vrsta VARCHAR(50) NOT NULL
);

CREATE TABLE Student (
	StudentID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FakultetID UNIQUEIDENTIFIER NOT NULL,
	Ime VARCHAR(20) NOT NULL,
	Prezime VARCHAR(20) NOT NULL,
	Godina SMALLINT NOT NULL,
	
	CONSTRAINT Student_Fakultet_FK FOREIGN KEY (FakultetID)
		REFERENCES Fakultet(FakultetID) ON DELETE CASCADE
);

GO

